### ISSUE TITLE
Bidirection layer does not work with Tensorflow 2.16.1 or higher

### ISSUE THREAD

**Issue by BDumphart** [philipperemy/keras-tcn#269]
Hi All,

I tried to use the bidirect_tcn.py (https://github.com/philipperemy/keras-tcn/blob/master/tasks/bidirect_tcn.py) file with the docker image 2.16.2-gpu-jupyter and the 2.17.0-gpu-jupyter, but could not use the Bidirectional layer as described. After switching to the docker image 2.15.0-gpu-jupyter it works, but in the README file it is stated that it should work up to tensorflow 2.17. 
I get the error message: "AttributeError: 'TCN' object has no attribute 'stateful"

Do you guys have any idea why this might be the case? If I use the 2.15 version, I get the error message that the CUDA kernel binaries are not compatible with the 9.0 from Tensorflow 2.15. 

Cheers,

Barry

**Comment by philipperemy** [comment]
@BDumphart 

Try that:

```python
"""
#Trains a TCN on the IMDB sentiment classification task.
Output after 1 epochs on CPU: ~0.8611
Time per epoch on CPU (Core i7): ~64s.
Based on: https://github.com/keras-team/keras/blob/master/examples/imdb_bidirectional_lstm.py
"""
import numpy as np
from tensorflow.keras import Input, Model
from tensorflow.keras.datasets import imdb
from tensorflow.keras.layers import Dense, Embedding, Bidirectional
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.src.saving import register_keras_serializable

from tcn import TCN


@register_keras_serializable()
class PatchTCN(TCN):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.stateful = False  # Manually add the stateful attribute


max_features = 20000
# cut texts after this number of words
# (among top max_features most common words)
maxlen = 100
batch_size = 32

print('Loading data...')
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)
print(len(x_train), 'train sequences')
print(len(x_test), 'test sequences')

print('Pad sequences (samples x time)')
x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = sequence.pad_sequences(x_test, maxlen=maxlen)
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)
y_train = np.array(y_train)
y_test = np.array(y_test)

inputs = Input(shape=(None,), dtype="int32")
x = Embedding(max_features, 128)(inputs)
x = Bidirectional(PatchTCN(64))(x)
# Add a classifier
outputs = Dense(1, activation="sigmoid")(x)
model = Model(inputs, outputs)
model.summary()

print(f'Backward TCN receptive field: {model.layers[2].backward_layer.receptive_field}.')
print(f'Forward TCN receptive field: {model.layers[2].forward_layer.receptive_field}.')

model.summary()
model.compile('adam', 'binary_crossentropy', metrics=['accuracy'])

print('Train...')
model.fit(
    x_train, y_train,
    batch_size=batch_size,
    validation_data=[x_test, y_test]
)

```

**Comment by philipperemy** [comment]
I fixed it in `3.5.2`. You can just upgrade the lib by:

```
pip install keras-tcn --upgrade
```
