### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'layer'

### ISSUE THREAD

**Issue by jiafatom** [philipperemy/keras-tcn#109]
My code works fine with keras-tcn==2.8.3 but not for 2.9.2.
I am using keras==2.2.5 and tensorflow==1.14.0, See the error below for 2.9.2, thanks!
```python
from tcn import TCN
batch_size, timesteps, input_dim = None, 20, 1
i = Input(batch_shape=(batch_size, timesteps, input_dim))
o = TCN(return_sequences=True)(i) 
```
it gives me error:
```python
  File "c:\programdata\anaconda3\envs\python368\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "c:\programdata\anaconda3\envs\python368\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 149, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))
AttributeError: in converted code:
    relative to c:\programdata\anaconda3\envs\python368\lib\site-packages:

    tcn\tcn.py:271 call *
        x = self.main_conv1D(x)
    tensorflow\python\keras\engine\base_layer.py:663 __call__
        inputs, outputs, args, kwargs)
    tensorflow\python\keras\engine\base_layer.py:1708 _set_connectivity_metadata_
        input_tensors=inputs, output_tensors=outputs, arguments=kwargs)
    tensorflow\python\keras\engine\base_layer.py:1795 _add_inbound_node
        input_tensors)
    tensorflow\python\util\nest.py:515 map_structure
        structure[0], [func(*x) for x in entries],
    tensorflow\python\util\nest.py:515 <listcomp>
        structure[0], [func(*x) for x in entries],
    tensorflow\python\keras\engine\base_layer.py:1794 <lambda>
        inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,

    AttributeError: 'tuple' object has no attribute 'layer'
```

**Comment by philipperemy** [comment]
The backend of keras-tcn>=2.9.2 changed from keras to tensorflow.keras.
Either update your imports:
- From "from keras.layers import <LayerName>"
- To "from tensorflow.keras.layers import <LayerName>"

Or downgrade to 2.8.3 by running "pip install keras-tcn==2.8.3"

**Comment by philipperemy** [comment]
https://github.com/philipperemy/keras-tcn/pull/110 I wrote a more explicit error message.
